#!/bin/bash

if [[ -z "${shome:-}" ]]; then
  shome="$(cd -P -- "$(dirname -- "${BASH_SOURCE}")/.." && pwd -P)"
fi

if [[ -z "${_AO_HOME:-}" ]]; then
  export _AO_HOME="$(dirname "$BUNDLE_GEMFILE")"
fi

source "$shome/libexec/_jason"
set -fue
