#!/bin/bash

#/ NAME
#/     ao -- alpha omega command line tool
#/
#/ SYNOPSIS
#/     ao <subcommand>

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/sbin/_treadstone"

require 'sub' "$BASH_SOURCE" "$@"
