#!/bin/bash

#/ NAME
#/     ao-build -- build assets, binaries, etc.
#/
#/ SYNOPSIS
#/     ao build [deploy_set...]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/sbin/_treadstone"

# parse the command-line

# entry point
function main {
  bundle exec cap "$@" deploy:lock deploy:build
}

require 'sub' "$BASH_SOURCE" "$@"
