#!/bin/bash

#/ NAME
#/     ao-compare -- compare workarea against the current deploy
#/
#/ SYNOPSIS
#/     ao compare [deploy_set...]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/sbin/_treadstone"

# parse the command-line

# entry point
function main {
  set -- $(for a in "$@"; do echo $a.app; done)
  bundle exec cap "$@" deploy:lock_compare deploy:compare
}

require 'sub' "$BASH_SOURCE" "$@"
