#!/bin/bash

#/ NAME
#/     ao-debug -- same as ao-hosts with debugging left on
#/
#/ SYNOPSIS
#/     ao debug [deploy_set...]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/sbin/_treadstone"

# parse the command-line

# entry point
function main {
  export LOCAL_ONLY=true
  {
    if [[ -n $1 ]]; then
      set -- $(for a in "$@"; do echo $a.echo; done)
      cap "$@"
    fi
  } 2>&1 | grep eea914aaa8dde6fdae29242b1084a2b0415eefaf | awk '{print $NF}' | sort -u
}

require 'sub' "$BASH_SOURCE" "$@"
