#!/bin/bash

#/ NAME
#/     ao-lock -- lock a deploy
#/
#/ SYNOPSIS
#/     ao lock [deploy_set...]
#/     ao lock migreate|compare [deploy_set...]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

# parse the command-line

# entry point
function main {
  case "${1}" in
    compare|migrate)
      nm_lock="${1}"; shift
      bundle exec cap "$@" deploy:dont_unlock "deploy:lock_${nm_lock}"
      ;;
    *)
      bundle exec cap "$@" deploy:dont_unlock deploy:lock
      ;;
  esac
}

require 'sub' "$BASH_SOURCE" "$@"
