#!/bin/bash

#/ NAME
#/     ao-migrate -- deploy to a migration workarea
#/
#/ SYNOPSIS
#/     ao migrate <deploy_host...>

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

# parse the command-line

# entry point
function main {
  bundle exec cap "$@" deploy:lock_migrate deploy:migrate
}

require 'sub' "$BASH_SOURCE" "$@"
