#!/bin/bash

#/ NAME
#/     ao-plan -- show what the deploy would do
#/
#/ SYNOPSIS
#/     ao plan [deploy_set...]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/sbin/_treadstone"

# parse the command-line

# entry point
function main {
  bundle exec cap "$@" deploy:lock deploy:plan
}

require 'sub' "$BASH_SOURCE" "$@"
