#!/bin/bash

#/ NAME
#/     ao-shell -- run a capistrano shell
#/
#/ SYNOPSIS
#/     ao shell [deploy_set...]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

# parse the command-line

# entry point
function main {
  bundle exec cap "$@" shell
}

require 'sub' "$BASH_SOURCE" "$@"
