#!/bin/bash

#/ NAME
#/     ao-task -- run a capistrano task remotely
#/
#/ SYNOPSIS
#/     ao task <task_name> deploy_set...

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/sbin/_treadstone"

# parse the command-line

# entry point
function main {
  local nm_task=$1; shift
  set -- $(for a in "$@"; do echo $a.app; done)
  bundle exec cap "$@" deploy:lock_migrate deploy:migrate "$nm_task"
}

require 'sub' "$BASH_SOURCE" "$@"
