#!/bin/bash

#/ NAME
#/     aoh -- ao-helper subbed script
#/
#/ SYNOPSIS
#/     aoh <ao_command>

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

if [[ -z "${_AO_USER_ARGS:-}" ]]; then
  save_command="$1"; shift
  export _AO_USER_ARGS="$@"
  set -- "$save_command" "$@"
fi

require 'sub' "$BASH_SOURCE" "$@"
