#!/bin/bash

#/ NAME
#/     unlock --
#/
#/ SYNOPSIS
#/     
#/     unlock
#/     unlock compare|migrate
#/

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require 'ao'

function aomain {
  case "${1}" in
    compare|migrate)
      nm_lock="${1}"; shift
      set -- $(for a in "$@"; do echo $a.app; done)
      cap "$@" deploy:began "deploy:unlock_${nm_lock}" deploy:finished
      ;;
    *)
      set -- $(for a in "$@"; do echo $a.app; done)
      cap "$@" deploy:began deploy:unlock deploy:finished
      ;;
  esac
}

require sub "$BASH_SOURCE" "$@"
