#!/bin/bash

#/ NAME
#/     restart --
#/
#/ SYNOPSIS
#/     
#/     restart
#/

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"
require 'ao'

function aomain {
  set -- $(for a in "$@"; do echo $a.app; done)
  bundle exec cap "$@" deploy:began deploy:lock deploy:restart deploy:finished
}

require sub "$BASH_SOURCE" "$@"
