#!/bin/bash

#/ NAME
#/     task --
#/
#/ SYNOPSIS
#/     
#/     task <task_name> 
#/

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"
require 'ao'

function aomain {
  local nm_task=$1; shift
  set -- $(for a in "$@"; do echo $a.app; done)
  cap "$@" deploy:began deploy:lock_migrate deploy:migrate "$nm_task" deploy:finished
}

require sub "$BASH_SOURCE" "$@"
