#!/bin/bash

#/ NAME
#/     aoh-stub -- aliases bin/xxx to bin/aoh xxx
#/
#/ SYNOPSIS
#/     aoh-sub

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"

# entry point
function main {
  exec "$shome/libexec/aoh" "$(basename "$0")" "$@"
}

if [[ -z "${_AO_USER_ARGS:-}" ]]; then
  export _AO_USER_ARGS="$@"
fi
require 'sub' "$BASH_SOURCE" "$@"
