#!/bin/bash

#/ NAME
#/     stage --
#/
#/ SYNOPSIS
#/     
#/     stage

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"
require 'ao'

function aomain {
  set -- $(for a in "$@"; do echo $a.app; done)
  bundle exec cap "$@" deploy:lock deploy:update_code deploy:symlink_next
}

require sub "$BASH_SOURCE" "$@"
