#!/bin/bash

#/ NAME
#/     unlock --
#/
#/ SYNOPSIS
#/     
#/     unlock
#/     unlock compare|migrate
#/

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"
require 'ao'

function aomain {
  case "${1}" in
    compare|migrate)
      nm_lock="${1}"; shift
      set -- $(for a in "$@"; do echo $a.app; done)
      bundle exec cap "$@" "deploy:unlock_${nm_lock}"
      ;;
    *)
      set -- $(for a in "$@"; do echo $a.app; done)
      bundle exec cap "$@" deploy:unlock
      ;;
  esac
}

require sub "$BASH_SOURCE" "$@"
