#!/bin/bash

#/ NAME
#/     stage --
#/
#/ SYNOPSIS
#/     
#/     stage

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require 'ao'

function aomain {
  set -- $(for a in "$@"; do echo $a.app; done)
  cap "$@" deploy:began deploy:lock deploy:update_code deploy:symlink_next deploy:finished
}

require sub "$BASH_SOURCE" "$@"
