#!/bin/bash

#/ NAME
#/     hosts --
#/
#/ SYNOPSIS
#/     
#/     hosts
#/

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"
require 'ao'

function aomain {
  export LOCAL_ONLY=true
  set -- $(for a in "$@"; do echo $a.echo; done)
  cap "$@" 2>&1 | grep eea914aaa8dde6fdae29242b1084a2b0415eefaf | awk '{print $NF}' | sort -u 2>&1
}

require sub "$BASH_SOURCE" "$@"
