#!/bin/bash

#/ NAME
#/     dna --
#/
#/ SYNOPSIS
#/     
#/     dna
#/

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"
require 'ao'

function aomain {
  export LOCAL_ONLY=true
  {
    set -- $(for a in "$@"; do echo $a.yaml; done)
    echo "eea914aaa8dde6fdae29242b1084a2b0415eefaf ---"
    bundle exec cap "$@"
  } 2>&1 | grep eea914aaa8dde6fdae29242b1084a2b0415eefaf | sed 's#eea914aaa8dde6fdae29242b1084a2b0415eefaf ##'
}

require sub "$BASH_SOURCE" "$@"
