#!/bin/bash

#/ NAME
#/     debug --
#/
#/ SYNOPSIS
#/     
#/     debug

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"
require 'ao'

function aomain {
  export LOCAL_ONLY=true
  set -- $(for a in "$@"; do echo $a.echo; done)
  cap "$@"
}

require sub "$BASH_SOURCE" "$@"
