#!/bin/bash

#/ NAME
#/     shell --
#/
#/ SYNOPSIS
#/     
#/     shell
#/

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"
require 'ao'

function aomain {
  set -- $(for a in "$@"; do echo $a.app; done)
  cap "$@" deploy:began shell deploy:finished
}

require sub "$BASH_SOURCE" "$@"
