#!/bin/bash

#/ NAME
#/     deploy --
#/
#/ SYNOPSIS
#/     
#/     deploy

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# define command line options:
#   var name, default, description, short option
DEFINE_boolean first "$FLAGS_FALSE" "first time signing off?"

# entry point
function main {
  if [[ "$#" = 0 ]]; then
    logger_fatal "must specify a semver"
    exit 1
  fi

  local ver_signoff="$1"; shift

  if [[ "$FLAGS_first" = "$FLAGS_FALSE" ]]; then
    git fetch -f origin refs/notes/deploys:refs/notes/deploys
  fi
  git notes --ref=deploys append -m "$ver_signoff signoff $LOGNAME $(date)"
  git push origin refs/notes/deploys
}

require sub "$BASH_SOURCE" "$@"
