#!/bin/bash -e

hst_proxy="${GATEWAY:=deploy}"

# remote arguments
git_url="$(git config --list | grep remote.origin.url | cut -d= -f2-)"

git_ref=$(cat .git/HEAD)
if echo "$git_ref" | egrep -q "^ref:"; then
  git_branch=$(echo "$git_ref" | awk '{print $1}' | cut -d/ -f3-)
  git_head=$(git show-ref --hash "$(echo "$git_ref" | awk '{print $2}')")
else
  git_branch=""
  git_head=$git_ref
fi

if [[ -z $git_head ]]; then
  echo "ERROR: could not find the SHA for HEAD" 1>&2
  exit 1
fi

ssh -t $hst_proxy alpha_omega_proxy_helper "$USER" "$git_url" "$git_branch:$git_head" "$@"
