#!/bin/bash -e

hst_proxy="${GATEWAY:=deploy}"

# remote arguments
git_url="$(git config --list | grep remote.origin.url | cut -d= -f2-)"
git_head="$(git log HEAD | head -1 | grep ^commit | awk '{print $2}')"

ssh $hst_proxy alpha_omega_proxy_helper "$USER" "$git_url" "$git_head" "$@"
