#!/bin/bash -e

hst_proxy="${GATEWAY:=deploy}"

# remote arguments
git_url="$(git config --list | grep remote.origin.url | cut -d= -f2-)"
git_branch="$(git branch | grep '^\*' | awk '{print $2}' | head -1)"
git_head="$(git show-ref HEAD | head -1 | awk '{print $1}')

if [[ -z $git_head ]]; then
  echo "ERROR: could not find the SHA for HEAD" 1>&2
  exit 1
fi

ssh -t $hst_proxy alpha_omega_proxy_helper "$USER" "$git_url" "$git_branch:$git_head" "$@"
