#!/bin/bash

#/ NAME
#/     remote-helper -- remotely builds a workarea
#/
#/ SYNOPSIS
#/     
#/     remote-heper deployer git_url git_spec deploy_comand deploy_args
#/

set -e
if [[ "$#" > 0 ]]; then
  if [[ "$1" = "--debug" ]]; then
    shift
    export FLAGS_debug=0
    set -x
  fi
fi

# entry point
function main {
  nm_deployer=$1; shift
  git_url=$1; shift
  git_spec=$1; shift
  cmd_deploy=$1; shift

  export _AO_DEPLOYER="$nm_deployer"

  git_branch="${git_spec%%:*}"
  git_sha="${git_spec##*:}"

  mkdir -p "$HOME/.deploy/$nm_deployer"
  cd "$HOME/.deploy/$nm_deployer"

  nm_project=$(basename $git_url .git)
  if [[ ! -d $nm_project ]]; then
    git clone -q $git_url
  fi

  cd $nm_project
  git fetch -q

  if [[ -z $git_branch || $git_branch = $git_sha ]]; then
    git reset -q --hard $git_sha
    git checkout -q $git_sha
  else
    git checkout -q --force $git_branch
    git reset -q --hard $git_sha
  fi

  git submodule -q update --init --recursive

  export _AO_EXTRA_BUNDLER_ARGS="--without development:test"
  bin/$cmd_deploy "$@"
}

# pass arguments to entry point
main "$@"
