#!/bin/bash

#/ NAME
#/     remote-helper -- remotely builds a workarea
#/
#/ SYNOPSIS
#/     
#/     remote-heper deployer git_url git_spec deploy_comand deploy_args
#/

set -e
if [[ "$#" > 0 ]]; then
  if [[ "$1" = "--debug" ]]; then
    shift
    export FLAGS_debug=0
    set -x
  fi
fi

# entry point
function main {
  pth_rvmrun=$1; shift
  nm_ruby=$1; shift
  nm_deployer=$1; shift
  git_url=$1; shift
  git_spec=$1; shift
  cmd_deploy=$1; shift

  git_branch="${git_spec%%:*}"
  git_sha="${git_spec##*:}"

  mkdir -p "$HOME/.deploy/$nm_deployer"
  cd "$HOME/.deploy/$nm_deployer"

  nm_project=$(basename $git_url .git)
  if [[ ! -d $nm_project ]]; then
    git clone -q $git_url
  fi

  cd $nm_project
  git fetch -q

  if [[ -z $git_branch || $git_branch = $git_sha ]]; then
    git reset -q --hard $git_sha
    git checkout -q $git_sha
  else
    git checkout -q --force $git_branch
    git reset -q --hard $git_sha
  fi

  git submodule -q update --init --recursive

  export _AO_DEPLOYER="$nm_deployer"
  local ruby_loader=""
  if [[ "$pth_rvmrun" != "x" ]]; then
    PATH="$PATH:/usr/local/rvm/bin:$HOME/.rvm/bin"
    ruby_loader="$pth_rvmrun $nm_ruby"
  fi
  $ruby_loader bundle check 2>&1 >/dev/null || { $ruby_loader bundle install --quiet --local --path vendor/bundle || bundle check > /dev/null; }
  $ruby_loader bundle exec ao $cmd_deploy "$@"
}

# pass arguments to entry point
main "$@"
