#!/bin/bash -e

which figlet 2>&- > /dev/null
bundle check || bundle --local --path vendor/bundle
exec bundle exec foreman start -f $(dirname $(dirname $0))/Procfile -c git=1,rollback=1,cap=0,stage=0,patch=0
